spring:
  datasource:
    url: jdbc:postgresql://db:5432/testdb
#    url: jdbc:postgresql://localhost:5423/testdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true