spring:
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:postgresql://localhost:5432/testdb
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: validate
    show-sql: true
#  flyway:
#    baseline-on-migrate: true
exception_message: Объект %s c id=%d не найден