spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true

exception_message: Объект %s c id=%d не найден

jwt:
  secret_access_key: Pax Pamir
  secret_refresh_key: Pax Renaissance
  life_time_access: 3
  life_time_refresh: 60
  subject: User details
api_name: api/v2