create table comment (id int8 generated by default as identity, content varchar(255) not null, task_id int8 not null,
primary key (id));

create table project (id int8 generated by default as identity, description varchar(255), title varchar(255),
primary key (id));

create table project_user (project_id int8 not null, user_id int8 not null, primary key (project_id, user_id));

create table tasks (id int8 generated by default as identity, task_date date default current_date,
description varchar(255), status varchar(255) default 'EMPTY', title varchar(255) not null, project_id int8 not null,
user_id int8 not null, primary key (id));

create table users (id int8 generated by default as identity, first_name varchar(255) not null,
last_name varchar(255) not null, login varchar(255) not null, password varchar(255) not null,
surname varchar(255), primary key (id));

alter table if exists users add constraint UKow0gan20590jrb00upg3va2fn unique (login);
alter table if exists comment add constraint FKfwc7uv5cfkqi3dnb2t20rnurc foreign key (task_id) references tasks;
alter table if exists project_user add constraint FKfscw5rga2yu389e705x9wg6kb foreign key (user_id) references users;
alter table if exists project_user add constraint FK4ug72llnm0n7yafwntgdswl3y foreign key (project_id) references project;
alter table if exists tasks add constraint FKekeburt7kaq2chv97jybdxnfm foreign key (project_id) references project;
alter table if exists tasks add constraint FK6s1ob9k4ihi75xbxe2w0ylsdh foreign key (user_id) references users;

insert into users (first_name,last_name,surname,login,"password") values('Тестовый','Бубислав','Палыч','palych','1111111'),
('Нетестовый','Варфоломей','Бубиславыч','buba','12345678'), ('Полутестовый','Евпатий','Варфоломеич','evpt','12345678');
insert into project (title,description) values ('Проект 1','програмистское'), ('Проект 2','людское');